### ISSUE TITLE
ksvaachen.de 도메인 이전

### ISSUE THREAD

**Issue by GyuminLee** [KSV-Aachen/Documentation#3]
https://domains.google/
에서 transfer 가능합니다

**Comment by highclef** [comment]
# Steps
1. Google에서 도메인 이전 신청: https://domains.google/ 에서 ksvaachen.de 기입
2. HostEurope에서 도메인 손절 신청: https://www.hosteurope.de/faq/domains/verwaltung/freigaben-domains-erteilen/
3. 다시 Google로 돌아와서 손절 코드 입력
![image](https://user-images.githubusercontent.com/20767186/148645216-4a7fcb87-34b5-4d61-ad0f-e06824ed7de0.png)
![image](https://user-images.githubusercontent.com/20767186/148645440-c4deb6cc-ac19-4b77-bc34-08325da49f45.png)
4. 도메인 관리 페이지: https://domains.google.com/registrar/ksvaachen.de
