### ISSUE TITLE
hosteurope 에서 자료 백업

### ISSUE THREAD

**Issue by GyuminLee** [KSV-Aachen/Documentation#4]

**Comment by GyuminLee** [comment]
@highclef ksv aachen google drive에 업로드 완료

**Comment by highclef** [comment]
@GyuminLee 저번에 말씀드린 자료만 올려놓으신 거죠? 집에 돌아가는 대로 제가 가지고 있는 자료들도 추가하겠습니다.

**Comment by GyuminLee** [comment]
@highclef 아뇨 제가 다 찾아서 올리긴했어요. 함 더 확인하시구 혹시 제가 놓친거 있으면 올려주세요!
