### ISSUE TITLE
gmail -> ksvaachen.de 메일서버 구축

### ISSUE THREAD

**Issue by GyuminLee** [KSV-Aachen/Documentation#5]
@highclef 도메인을 사용한 메일을 포워딩만 ksv gmail로 오도록 하셔도 될듯해요.

**Comment by highclef** [comment]
contact@ksvaachen.de -> aachenksv@gmail.com Forwarding 설정 완료
https://support.google.com/domains/answer/3251241?hl=en&ref_topic=6293345
