### ISSUE TITLE
개인정보 처리방침, 사용자데이터 삭제, 서비스 약관 만들기

### ISSUE THREAD

**Issue by GyuminLee** [KSV-Aachen/Documentation#6]
![image](https://user-images.githubusercontent.com/8346057/146995904-5a97ec58-1e42-4f81-ae4a-e1b7768a064d.png)

위의 내용이 들어간 웹 페이지가 필요합니다..(insta 연동하는데 필요)
application 등록하기가 많이 빡세졌네요.. 

페이지는 저희가 만들 수 있으니 내용만 학생회와 상의 후에 부탁드립니다. (이게 완료되어야지 instagram 연동 가능)

**Comment by GyuminLee** [comment]
@highclef 이건 지영씨 task입니다..

**Comment by highclef** [comment]
- Privacy Policy: https://www.privacypolicies.com/live/a0492a15-a85d-4f4f-ad4e-0e958d7b0662
Generator: https://app.privacypolicies.com/

- Terms of Service: https://www.termsofservicegenerator.net/live.php?token=DxOiv9bPStBDxOWbfq3g9ELLwYJj9tuO
Generator: https://www.termsofservicegenerator.net/
